### ISSUE TITLE
Do use the form <URL>

### ISSUE THREAD

**Issue by parabolapersuader** [0x6b/copy-selection-as-markdown#100]
Currently, the extension does not check for the text and the link. The result is 

```
[$URL][]

[$URL]: $URL
```

instead of the simpler

```
<$URL>
```

**Comment by 0x6b** [comment]
@parabolapersuader Thanks for opening an issue but I cannot figure out what your problem is. Can you please follow the issue template https://raw.githubusercontent.com/0x6b/copy-selection-as-markdown/master/.github/ISSUE_TEMPLATE.md.

**Comment by alexanderadam** [comment]
I guess I can help:

Markdown knows at least three kinds of links. Two of them are already available via the extension (`[caption](http://...)` and referenced `[caption][1] [1]: http://`).

But the third one is a short variant in cases where caption and URL are identical:

```markdown
Short variant:
<https://eff.org>

Long variant:
[https://eff.org](https://eff.org)
```

You can see its [reference here](https://www.markdownguide.org/basic-syntax/#links).

This also works for emails (`<hello@example.org>`).

**Comment by 0x6b** [comment]
Thanks, @alexanderadam, for the elaboration. Since the original poster hasn't returned, I'll go ahead and close this issue.

**Comment by alexanderadam** [comment]
OP's request still sounds reasonable though. :wink: But I find [my link issue](https://github.com/0x6b/copy-selection-as-markdown/issues/126) more important. :laughing:
