### ISSUE TITLE
[Enhancement] include link to source in config options

### ISSUE THREAD

**Issue by gandrille** [0x6b/copy-selection-as-markdown#11]
Can you add a checkbox in the configuration page to decide if the link to the source web page should be included at the beginning of the copied text ?

PS: in all cases, thanks a LOT for your extension !

**Comment by 0x6b** [comment]
Hi @gandrille, appreciate your feedback!

Do you mean you don't want the extension include link to the source in the beginning of copied text, just want a copied markdown text only, right? Let me confirm your use case. Thank you.

**Comment by gandrille** [comment]
Hi 0x6b,
Yes, this is what I mean.

**Comment by 0x6b** [comment]
@gandrille, I got your point. Give me some time to implement!

**Comment by 0x6b** [comment]
@gandrille, I have just released [v0.4.0](https://github.com/0x6b/copy-selection-as-markdown/releases/tag/v0.4.0) which includes the setting. Please try this on your setup. If you find any unexpected behavior, please file an issue. Thanks!

https://addons.mozilla.org/en-US/firefox/addon/copy-selection-as-markdown/versions/0.4.0

**Comment by gandrille** [comment]
Just perfect! This is the exact behavior I was expecting.
Thanks a lot!

PS: if you have a paypal account, I would be happy to offer you a beer ;-)
see for example http://zim-wiki.org/contribute.html
This is ssth you can include in the README.md of your github repository

**Comment by 0x6b** [comment]
@gandrille thanks a lot for your confirmation. Setting up a PayPal for a beer will be on my todo list. Anyway thanks!
