### ISSUE TITLE
chrome version is not working with `TypeError: e.DT is not a constructor`

### ISSUE THREAD

**Issue by 0x6b** [0x6b/copy-selection-as-markdown#125]
The chrome version is not working with following error message.

```
TypeError: e.DT is not a constructor
```

No time to fix it for the moment though.

**Comment by 0x6b** [comment]
Works now on v0.22.0. You still need to build it locally by yourself, though.

**Comment by lamyergeier** [comment]
@0x6b  Please check: [[Does not works in Chrome with 0.22.0 version · Issue #130 · 0x6b/copy-selection-as-markdown](https://github.com/0x6b/copy-selection-as-markdown/issues/130)](https://github.com/0x6b/copy-selection-as-markdown/issues/130)
