### ISSUE TITLE
Sometimes links are double converted

### ISSUE THREAD

**Issue by alexanderadam** [0x6b/copy-selection-as-markdown#126]
Hello kaoru,

long time no see.
Sometimes I'm running into double converted links:

1. use these settings like shown in the attachment
2. Copy the content of [this comment](https://github.com/citra-emu/citra-android/issues/34#issuecomment-667542465)

instead of

```markdown
[according to the Android TV developer documentation](https://developer.android.com/training/tv/start/start) there's also the…
```

it is

```markdown
[[according to the Android TV developer documentation](https://developer.android.com/training/tv/start/start)](https://developer.android.com/training/tv/start/start) there's also the…
```

![image](https://github.com/0x6b/copy-selection-as-markdown/assets/372620/0262dc4b-0ba9-445e-b5ee-58d211eb8e46)

**Comment by 0x6b** [comment]
@alexanderadam I believe this issue stems from GitHub (or, the underlying editor component). See https://github.com/orgs/community/discussions/65235. I haven't observed this behavior anywhere but on GitHub. I do feel it's annoying, but there's nothing I can do unfortunately.

**Comment by alexanderadam** [comment]
Nice find! I'll close this issue here then.
