### ISSUE TITLE
syntax feature request

### ISSUE THREAD

**Issue by evert-mouw** [0x6b/copy-selection-as-markdown#13]
Wow, I just discovered this, thanks for creating this! Very handy when making notes.
It's good as it is. But maybe it would be possible to support different Markdown syntax options? (Also inserting the current date as an option would be great and having the option to cite the source URL/title/date at the bottom.) 
https://github.com/domchristie/turndown#options

**Comment by 0x6b** [comment]
@evert-mouw good to hear you like my add-on! Let me implement one by one as it may need options page overhaul.

**Comment by 0x6b** [comment]
v0.5.0 which includes this feature is under review by Mozilla

**Comment by evert-mouw** [comment]
Wow even more than I'd hoped for, good work, I'm going to use this very often!

**Comment by 0x6b** [comment]
@evert-mouw thanks! For unknown reason, review from Mozilla takes really long time. I pushed dependency-updates only version to kick the review and got instant approval. Please grab the update from you add-on page (Tools -> Add-ons -> Gear icon -> Check for Updates) or get it from [here](https://addons.mozilla.org/en-US/firefox/addon/copy-selection-as-markdown/versions/?page=1#version-0.5.2). Please open a new issue if you find any issue.
