### ISSUE TITLE
Nested link markup generated

### ISSUE THREAD

**Issue by brlin-tw** [0x6b/copy-selection-as-markdown#133]
**Actual Result**

```markdown
[[New Issue · 0x6b/copy-selection-as-markdown](https://github.com/0x6b/copy-selection-as-markdown/issues/new)](https://github.com/0x6b/copy-selection-as-markdown/issues/new)
```

### INPUT

```html

```

### OUTPUT

```markdown

```

### Source URL

https://github.com/0x6b/copy-selection-as-markdown/issues/new

**Expected Result**

```markdown
[New Issue · 0x6b/copy-selection-as-markdown](https://github.com/0x6b/copy-selection-as-markdown/issues/new)
```

**Comment by brlin-tw** [comment]
Issue still reproduced after I re-install the addon:

[[Nested link markup generated · Issue #133 · 0x6b/copy-selection-as-markdown](https://github.com/0x6b/copy-selection-as-markdown/issues/133)](https://github.com/0x6b/copy-selection-as-markdown/issues/133)

**Comment by 0x6b** [comment]
@brlin-tw Thank you for reporting your issue. I do feel it's annoying, but there's nothing I can do unfortunately.

Duplicate: #126
Ref.: https://github.com/orgs/community/discussions/65235.
