### ISSUE TITLE
Nothing gets copied to clipboard

### ISSUE THREAD

**Issue by Korodny** [0x6b/copy-selection-as-markdown#18]
Firefox 60.4.0esr on Debian Testing, just installed the extension from AMO.

Trying to copy a selection of text containing headings, numbered lists etc. from [this page](https://urukrama.wordpress.com/openbox-guide/#xcompmgr), nothing ever reaches the clipboard.

Here's the only output I get in the web console:

    JQMIGRATE: Migrate is installed, version 1.4.1
    _static:9:542
    TypeError: a.getAttribute(...) is null
    Stack trace:
    getSelectionAsMarkdown@moz-extension://0bd6bf0b-eb6e-469a-922c-b2e7fb3b7852/copy.js:161:12
    main@moz-extension://0bd6bf0b-eb6e-469a-922c-b2e7fb3b7852/copy.js:94:21
    copy.js:122:5

**Comment by 0x6b** [comment]
@Korodny thank you for the issue. I found an issue where the plugin failed to handle `a` tag without `href` attribute. Will release new version shortly.

**Comment by 0x6b** [comment]
@Korodny I just published v0.6.1 which fixes the issue. Please grab the update from you add-on page (Tools -> Add-ons -> Gear icon -> Check for Updates). Please open a new issue if you find any issue. Thanks!

**Comment by Korodny** [comment]
@0x6b Updated to the new version, stuff gets properly added to clipboard now. I did notice a few minor things though, do you want new issues for all of those? I copied chapters content, 1 and 2 including the headings from the above page and had a look at the result:

1. highlighted text is deselected after it is copied to clipboard. traditional copy-to-clipboard doesn't do that
2. when I paste the clipboard content into my text editor, dots in headings are escaped with a backslash
3. the extension treats the entire content I copied as a blockquote, i.e. all lines start with ">". Not sure what's causing this
4. nested lists seem to be a problem (i.e. they're just treated as one giant list). not sure how well markdown handles such a case though, never had to deal with nested lists in markdown

**Comment by Korodny** [comment]
The issue with escaped dots in headings is fixed in 0.7.0.

Sorry, about the 'Append quote' configuration option - missed that. Is this enabled by default? I can't remember activating it (I did fool around a bit though, so it's entirely possible). If it is, I'd open a new issue about it ;-)

**Comment by 0x6b** [comment]
- I did nothing for esapes in headings. Please watch (and comment on) #21 going forward. Note that I won't address this in short term as it needs some time ([contribution](https://github.com/0x6b/copy-selection-as-markdown/blob/master/CONTRIBUTING.md) welcome!)
- The add-on appends quote by default. You don't have to open an issue as you can set via preference as you wish.

**Comment by Korodny** [comment]
Well, I question the decision to make "append quote" the default ;) It's nice to have as an option, but why make it default?

**Comment by 0x6b** [comment]
I got your point. It's by default as copied text is literally a quote for me. I won't surprise existing users by changing default setting.
