### ISSUE TITLE
Copy links

### ISSUE THREAD

**Issue by Changaco** [0x6b/copy-selection-as-markdown#32]
I think it would be great if this extension also supported copying individual links in a page as Markdown like <https://github.com/chitsaou/copy-as-markdown> does.

**Actual Result**

Right-click on a link in a page, no option to copy the link as Markdown is available in the menu.

**Expected Result**

An option titled "Copy link as Markdown" or "Copy \[Link Content](URL)" is present in the right-click menu.

**Comment by 0x6b** [comment]
@Changaco appreciate your feedback. That feature would be a natural fit for the add-on. Give me some time to implement. Thanks!

**Comment by 0x6b** [comment]
@Changaco I just published [v0.11.0](https://github.com/0x6b/copy-selection-as-markdown/releases/tag/v0.11.0) which includes right-click-to-copy on a link. Update the add-on from you add-on page (Tools -> Add-ons -> Gear icon -> Check for Updates). Please open a new issue if you find any issue. Thanks!
