### ISSUE TITLE
[Feature suggestion] syntax option for images copied as html <img>

### ISSUE THREAD

**Issue by doneykoo** [0x6b/copy-selection-as-markdown#36]
Because for many markdown parsers, `![](url)` does not support proper width height property.

It would be great to have syntax option, to copy img just as `<img>` into copied markdown result. Also maybe copy the `width` `height` property directly from selection.

**Comment by 0x6b** [comment]
Thank you for the suggestion. I don't have such use case at this moment but will implement in the future release. Of course pull request would be appreciated.

**Comment by 0x6b** [comment]
Hi @doneykoo I just released [v0.14.0](https://github.com/0x6b/copy-selection-as-markdown/releases/tag/v0.14.0) which introduce new setting "**Use `img` tag for image**." Hope this helps your use case. Open an issue if you find any problem. Thanks!

**Comment by doneykoo** [comment]
@0x6b great job! I've just tried it, and it was great, working well and super handy. Thank you!
