### ISSUE TITLE
Bring Save button to the bottom

### ISSUE THREAD

**Issue by vstepaniuk** [0x6b/copy-selection-as-markdown#37]
Is it possible to bring Save button in Firefox add-on preferences to the bottom? or make it auto save? thank you

**Comment by 0x6b** [comment]
Thank you for the suggestion. Yes the small **save** button could be difficult to find and some space to improvement. I'll try to address the issue.

**Comment by 0x6b** [comment]
Hi @vstepaniuk, just released [v0.13.0](https://github.com/0x6b/copy-selection-as-markdown/releases/tag/v0.13.0) which brings save button to the button (as well as the top). Please grab the update from you add-on page. Open a new issue if you find any issue please. Thanks!
