### ISSUE TITLE
Option to disable link styling

### ISSUE THREAD

**Issue by zebzorb** [0x6b/copy-selection-as-markdown#43]
I really like using this extension to paste formatted text into Discord, but Discord unfortunately doesn't support links `[like this](https://example.com)`. It just shows that without formatting and makes the `https://example.com` part clickable.

So an option to either disable link styling entirely and only copy the link's text (so the above example would look `like this`) or an option to remove the brackets but still have the URL in parentheses `like this (https://example.com)` would be much appreciated!

**Comment by 0x6b** [comment]
Agreed. I have similar use case with Slack. Allow me think how I can implement your request.

**Comment by 0x6b** [comment]
Hey @zebzorb I just released [v0.15.0](https://addons.mozilla.org/en-US/firefox/addon/copy-selection-as-markdown/versions/0.15.0) which implements new setting "Disable link styling." Hope this helps your use case. Open an issue if you find any problem. Thanks!

**Comment by zebzorb** [comment]
Hey, thanks so much! Works great.
