### ISSUE TITLE
Support for Chrome and Hosting on https://add0n.com

### ISSUE THREAD

**Issue by anishmittal2020** [0x6b/copy-selection-as-markdown#50]
WebExtension API for Firefox and Chrome is probably not very different. It would be great if its also supported in Chrome as it has much larger userbase and the extension will get more attention from many new users.

Many opensource extensions are hosted at https://add0n.com/index.html; such as [Reader View :: add0n.com](https://add0n.com/chrome-reader-view.html). Most of them are cross-browser extensions.

**Comment by 0x6b** [comment]
Appreciate your feedback @anishmittal2020 ! I'm occasional Google Chrome user and am missing my extension is there. I'll consider making this cross platform. Thank you.

**Comment by 0x6b** [comment]
I'm slowly working on Chrome support at [chromium](https://github.com/0x6b/copy-selection-as-markdown/tree/chromium) branch. Initial implemention works for me but release will take some more time as there's still a lot to do. Hosting on add0n.com won't happen though.

**Comment by 0x6b** [comment]
I've setup [$5 GitHub one-time sponser](https://github.com/sponsors/0x6b?frequency=one-time) for those who want to see this addon on the Chrome Web Store (which needs 5 USD registration fee.) Will close this issue hoping someone will help us🤞
