### ISSUE TITLE
Angle brackets not escaped

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [0x6b/copy-selection-as-markdown#53]
**Actual Result**
```
/* --- copy-selection-as-markdown debug information --- */ copy.js:54:14
/* --- INPUT ------------------------------------------ */ copy.js:55:14
&lt;Location&gt; copy.js:56:14
/* --- OUTPUT------------------------------------------ */ copy.js:57:14
<Location> copy.js:58:14
/* --- URL -------------------------------------------- */ copy.js:59:14
https://httpd.apache.org/docs/current/mod/core.html#directory copy.js:60:14
/* ---------------------------------------------------- */
```

**Expected Result**

`\<Location\>` or angle brackets escaped as HTML entities.

**Comment by 0x6b** [comment]
@Lin-Buo-Ren Appreciate your efforts to report this! Will take a look next week or later.

**Comment by 0x6b** [comment]
Another update for @Lin-Buo-Ren! in tandem with #51. v0.17.0 includes this feature with "Replace angle brackets (<code><></code>) with HTML entities" option. Hope this helps. Thanks!
