### ISSUE TITLE
Bump Turndown to latest version

### ISSUE THREAD

**Issue by ngirard** [0x6b/copy-selection-as-markdown#56]
Hey,
I've just discovered this extension and I'm very satisfied with its options and functionalities: thanks for your work !

I saw that Turndown recently released a new major version: would you mind including it to a new version of c-s-a-m ?

Cheers!

**Comment by 0x6b** [comment]
@ngirard thanks a lot for the feedback which motivates me keeping this add-on public. As noted at the [Turndown's README](https://github.com/domchristie/turndown/tree/e2c64f121a170ad04363c7da3bbf978ebcde5f7f#escaping-markdown-characters), new escaping rules is quite aggressive and it caused a lot of headache while evaluating it last year. Anyway I will try to revisit. Thank you.

**Comment by 0x6b** [comment]
One question; do you have particular reason/feature for requesting upgrade? I know latest would be greatest but if you have any let me know. Thanks!
