### ISSUE TITLE
implementation question

### ISSUE THREAD

**Issue by boulderob** [0x6b/copy-selection-as-markdown#61]
Quick implementation question if you have the time and or know the answer.  

Since to my knowledge when you select on a page in a browser, the selection is plain text and not the underlying *html* source representing the text, how does turndown (which you pass the selection off to) know that selected text containing "code blocks" are indeed fenced code blocks?  I hope that makes sense.  I looked in your code and i can't find that necessary "magic".  Perhaps i'm missing something obvious though.

Any thoughts greatly appreciated
Thanks

**Comment by 0x6b** [comment]
@boulderob,

[`src/lib/util.js`](https://github.com/0x6b/copy-selection-as-markdown/blob/master/src/lib/util.js#L88-L126) will extract HTML representation from your selection. Select some text on this page, open Web Console, paste following snippet, press enter and see how the magic looks like.

```js
const container = document.createElement("div");
const selection = document.getSelection();
for (let i = 0; i < selection.rangeCount; i++) {
  container.appendChild(selection.getRangeAt(i).cloneContents());
}
console.log(container.innerHTML);
```

Hope this helps.

**Comment by boulderob** [comment]
Thanks @0x6b!!  It's hard to find info related to this with online search but i dug further yesterday and it appears the magic is cloneContents.  Your suggestion and code snippet only confirm it!

**Comment by 0x6b** [comment]
Good to hear that. Will close the issue. Thanks!
