### ISSUE TITLE
Fenced code blocks don't work as they should

### ISSUE THREAD

**Issue by t-e-r-m** [0x6b/copy-selection-as-markdown#62]
**Browser**: >=FF 74
**Extension version**: 0.18.0

# Actual Result

```
/* --- copy-selection-as-markdown debug information --- */
/* --- INPUT ------------------------------------------ */
<div class="toc"><ol><li class="L2"><a href="https://git-annex.branchable.com/walkthrough/#index21h2"></a>
		</li>
	</ol>
</div>




<h2><a name="index1h2"></a><a href="https://git-annex.branchable.com/walkthrough/creating_a_repository/">creating a repository</a></h2>
<p>This is very straightforward.</p>

<pre><code>$ mkdir ~/annex
$ cd ~/annex
$ git init
$ git annex init
</code></pre>
/* --- OUTPUT------------------------------------------ */
## [creating a repository](https://git-annex.branchable.com/walkthrough/creating_a_repository/)

This is very straightforward.

~
$ mkdir ~/annex
$ cd ~/annex
$ git init
$ git annex init

~
/* --- URL -------------------------------------------- */
https://git-annex.branchable.com/walkthrough/#index5h2
/* ---------------------------------------------------- */
```
It seems to be the same for ```.
I also checked the sample input at 
http://domchristie.github.io/turndown/
in a different file, which ~~reproduced~~ does not reproduce this issue.

# Expected Result
```
/* --- OUTPUT------------------------------------------ */
## [creating a repository](https://git-annex.branchable.com/walkthrough/creating_a_repository/)

This is very straightforward.

~~~
$ mkdir ~/annex
$ cd ~/annex
$ git init
$ git annex init

~~~
```

**Comment by 0x6b** [comment]
@t-e-r-m, really appreciate your time to report the issue.

> I also checked the sample input at
> http://domchristie.github.io/turndown/
> in a different file, which reproduced this issue.

I cannot reproduce the issue on Turndown itself, but can see with the extension. I'll look into the situation but unfortunately I have not enough bandwidth to fix it in short term. Thank you.

**Comment by t-e-r-m** [comment]
> I cannot reproduce the issue on Turndown
I didn't mean to write that, sorry. I meant to write that there's no issues in turndown. Must've fudged something in the edits.
I've edited my post accordingly.

> I'll look into the situation but unfortunately I have not enough bandwidth to fix it in short term.
That's fine.

Love the extension, BTW.

**Comment by 0x6b** [comment]
I see. Thanks for your clarity!

**Comment by 0x6b** [comment]
@t-e-r-m, I gave a quick look and found a root cause of the issue. Will release new version soon. The issue had been there since [v0.5.0](https://github.com/0x6b/copy-selection-as-markdown/commit/f054cff249dafdd71fa761d1d84847103ccc8c56)! Why I can't notice this for over a year??
