### ISSUE TITLE
Using regular expressions in the title substitution

### ISSUE THREAD

**Issue by viktomas** [0x6b/copy-selection-as-markdown#68]
## Problem to solve

Some titles contain strings that are not desirable in the final markdown link. The [title substitution](https://github.com/0x6b/copy-selection-as-markdown#advanced) currently solves this problem by specifying strings that get removed.

The problem is that the current functionality only allows static strings. We can't remove dynamically generated parts of the title.

### Example

I use the extension to copy Issue links from GitLab. CMD+SHIFT+E copies

```markdown
[Automated CHANGELOG entries creation (#198) · Issues · GitLab.org / gitlab-vscode-extension · GitLab](https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/issues/198)
```

The current substitution can remove ` · Issues · GitLab.org / gitlab-vscode-extension · GitLab` but it can't handle the `(#198)` bit.

## Proposal

Allow user to specify a regular expression. A simple solution might be to recognise strings that are wrapped in `/exp/` and not escape those. That shouldn't introduce breaking change (unless someone was escaping titles with `/<something>/` in them.

## Additional details

The logic that uses `regex-escape` to convert the title substitution to a regular expression: https://github.com/0x6b/copy-selection-as-markdown/blob/master/packages/core/src/copy.js#L68

**Comment by 0x6b** [comment]
@viktomas: Appreciate your time for this enhancement request! Your suggestion makes sense for me. Let me consider how I can implement this.

**Comment by viktomas** [comment]
@0x6b Would you like me to try and implement this enhancement? How does the "prposal" in the description sound?

**Comment by 0x6b** [comment]
@viktomas sorry for delay on my end. Of course you can try to implement the feature! Proposal looks good to me. (If we'd like to avoid breaking change completely, we can introduce new dedicate textarea for regex substitution.)

**Comment by 0x6b** [comment]
@viktomas v0.21.0, which includes your PR #80, is just published. Thanks much for your contribution!
