### ISSUE TITLE
Unable to use when in reader view

### ISSUE THREAD

**Issue by ngirard** [0x6b/copy-selection-as-markdown#74]
A very common workflow of mine is to toggle the reader view from Firefox (using Ctrl+Alt+r) in order to simplify the contents of a page, then copy some or all of its contents.

Unfortunately, when in reader view (and the current url has switched to `about:reader?url=https...`), Copy-selection-as-markdown cannot be used any more.

Could this be fixed ?
Could it be related to #70 ?

Cheers, and thanks for your work & dedication !

**Comment by 0x6b** [comment]
@ngirard Unfortunately your problem cannot be fixed, and is not related to #70. For security reason, any extensions cannot inject content script to `about:` URLs (other than `about:blank`) including the reader view. You can find relevant bug at [1371786 - Allow content scripts on reader mode pages](https://bugzilla.mozilla.org/show_bug.cgi?id=1371786).

At this moment I can't fix this so will close the issue, but appreciate your time for opening the issue. Let me know anything else I can do for you.

**Comment by ngirard** [comment]
Hey, thanks for your detailed explanation.
Those browsers' limitations are a real pain in the ass...
Would it make sense for your extension to offer to transform the contents of the clipboard, then ? If not, never mind -- I'll keep processing these html contents by hand using Pandoc. Not a big deal !
