### ISSUE TITLE
Not working on some pages

### ISSUE THREAD

**Issue by alexanderadam** [0x6b/copy-selection-as-markdown#82]
**Actual Result**

The extension doesn't seem to copy anything on [the Thunderbird FAQ](https://support.mozilla.org/en-US/products/thunderbird/how).
Is this some restriction? Or is this a security feature of firefox?

**Comment by 0x6b** [comment]
@alexanderadam Thank you for the issue. Yes this is security feature of Firefox, which restricted running anyextension from being injected to some Mozilla related sites. Please see [#57](https://github.com/0x6b/copy-selection-as-markdown/issues/57) for how to enable this extension work with the site. Thanks!

**Comment by 0x6b** [comment]
Will update README and close this issue.
