### ISSUE TITLE
Add option to strip part the title begining from a spefic string

### ISSUE THREAD

**Issue by peace2000** [0x6b/copy-selection-as-markdown#96]
Hi, many people don't necessarily know how to use regex, so could you consider adding an option to strip part of the title, begining from a specific string of text?

For e.g., many sites use vertical lines to separate multiple titles in tabs. One tab title could for e.g. be:

`Something | Strange - in the neighborhood`

So in this case, I want to drop everything, begining from:  " | " (vertical line and spaces).

So the result would be:
`Something`

I tried a regex code:

`\s(.*)`

But it didn't work, even though I used this site: https://regex101.com/ to verify it.

**Comment by 0x6b** [comment]
@peace2000 thank you your issue. That regex code works for me. You might forgot surrounding it with `/`. Please try again with `/\s.*/`, or more specifically with `/\s\|.*/` for your use case.

For adding new option, it might cause unexpected result as title delimiter is not standardized in any way so I prefer current geeky but granular control. Also precedence between preferences (that possible new option and current substitution box) could be unintuitive. I'll keep current implementation as is but PR would be welcomed. Thanks!

**Comment by peace2000** [comment]
Hi, thanks for the rule. It works as intended.

I didn't mean that specific characters should automatically or presumably considered as delimiters, as web pages do use different characters to separate texts, that's true. I suggested that users could have an option to freely choose which characters or text strings would be used to remove stuff in a way that instead of removing the exact string, there would be an option "remove everything after this string" or "remove everything beginning from this string".

(Sorry if I was unclear in my previous messages). :)

But anyway, I'm happy with the rule you provided. Thanks!

**Comment by 0x6b** [comment]
Glad the rule worked for you. I understood your point! I will close this issue for now but the request is noted. Once I have a time to rethink the settings (which has room for improvement I know) I will revisit this. Thanks!
